project:
  type: manuscript

article:
  file: index.qmd

format:
  html:
    toc: true
    number-sections: true
  pdf:
    toc: true
    number-sections: true
    keep-tex: true
    cite-method: biblatex
  docx:
    toc: true
    number-sections: true

execute:
  freeze: auto